$imagesDir = "e:\V2 Studio\images"
$renames = [ordered]@{
    "studiobychar studio by char 1.webp"   = "studiobychar studio by char solar halo.webp"
    "studiobychar studio by char 2.webp"   = "studiobychar studio by char grey sofa and orange chair studio.webp"
    "studiobychar studio by char 3.webp"   = "studiobychar studio by char podcast interview mixed guests.webp"
    "studiobychar studio by char 4.webp"   = "studiobychar studio by char podcast interview wicker chairs.webp"
    "studiobychar studio by char 5.webp"   = "studiobychar studio by char podcast setup vertical.webp"
    "studiobychar studio by char 6.webp"   = "studiobychar studio by char podcast interview closeup.webp"
    "studiobychar studio by char 7.webp"   = "studiobychar studio by char podcast setup studio lights.webp"
    "studiobychar studio by char 8.webp"   = "studiobychar studio by char podcast on velvet sofa.webp"
    "studiobychar studio by char 9.webp"   = "studiobychar studio by char empty podcast desk.webp"
    "studiobychar studio by char 10.webp"  = "studiobychar studio by char velvet sofa flower decor.webp"
    "studiobychar studio by char 11.webp"  = "studiobychar studio by char man on velvet sofa with mic.webp"
    "studiobychar studio by char 12.webp"  = "studiobychar studio by char studio plants on table.webp"
    "studiobychar studio by char 13.webp"  = "studiobychar studio by char close up podcast host guest.webp"
    "studiobychar studio by char 14.webp"  = "studiobychar studio by char neon camera logo window inside.webp"
    "studiobychar studio by char 15.webp"  = "studiobychar studio by char neon camera logo window outside.webp"
    "studiobychar studio by char 16.webp"  = "studiobychar studio by char neon camera logo window closeup.webp"
    "studiobychar studio by char 17.webp"  = "studiobychar studio by char podcast set a wicker chairs.webp"
    "studiobychar studio by char 18.webp"  = "studiobychar studio by char neon camera logo window wide.webp"
    "studiobychar studio by char 19.webp"  = "studiobychar studio by char grey sofa white curtains plants.webp"
    "studiobychar studio by char 20.webp"  = "studiobychar studio by char grey sofa closeup.webp"
    "studiobychar studio by char 21.webp"  = "studiobychar studio by char grey sofa white curtains plants v2.webp"
    "studiobychar studio by char 22.webp"  = "studiobychar studio by char grey sofa black stool rug.webp"
    "studiobychar studio by char 23.webp"  = "studiobychar studio by char grey sofa black stool rug v2.webp"
    "studiobychar studio by char 24.webp"  = "studiobychar studio by char neon camera logo window inside reflection.webp"
    "studiobychar studio by char 25.webp"  = "studiobychar studio by char neon camera logo window blue line art.webp"
    "studiobychar studio by char 26.webp"  = "studiobychar studio by char podcast set a 1 pax.webp"
    "studiobychar studio by char 27.webp"  = "studiobychar studio by char studio equipment stand purple backdrop.webp"
    "studiobychar studio by char 28.webp"  = "studiobychar studio by char studio room wide curtains.webp"
    "studiobychar studio by char 29.webp"  = "studiobychar studio by char studio room chairs table curtains.webp"
    "studiobychar studio by char 30.webp"  = "studiobychar studio by char grey sofa minimalist.webp"
    "studiobychar studio by char 31.webp"  = "studiobychar studio by char studio room rug neon logo view.webp"
    "studiobychar studio by char 32.webp"  = "studiobychar studio by char studio room wide curtains rug.webp"
    "studiobychar studio by char 33.webp"  = "studiobychar studio by char studio entrance neon logo closeup.webp"
    "studiobychar studio by char 34.webp"  = "studiobychar studio by char studio room chairs stools curtains.webp"
    "studiobychar studio by char 35.webp"  = "studiobychar studio by char cane chair green plant.webp"
    "studiobychar studio by char 36.webp"  = "studiobychar studio by char mirror reflection studio interior.webp"
    "studiobychar studio by char 37.webp"  = "studiobychar studio by char podcast set b 2 pax.webp"
    "studiobychar studio by char 38.webp"  = "studiobychar studio by char grey sofa closeup v2.webp"
    "studiobychar studio by char 39.webp"  = "studiobychar studio by char studio room equipment mezzanine.webp"
    "studiobychar studio by char 40.webp"  = "studiobychar studio by char studio lighting equipment stands.webp"
    "studiobychar studio by char 41.webp"  = "studiobychar studio by char cane chair green plant v2.webp"
    "studiobychar studio by char 42.webp"  = "studiobychar studio by char studio lighting stands white wall.webp"
    "studiobychar studio by char 43.webp"  = "studiobychar studio by char black backdrop studio lights.webp"
    "studiobychar studio by char 44.webp"  = "studiobychar studio by char podcast set c 1 pax velvet sofa.webp"
    "studiobychar studio by char 45.webp"  = "studiobychar studio by char studio room wide mezzanine v2.webp"
    "studiobychar studio by char 46.webp"  = "studiobychar studio by char white studio room chairs table v2.webp"
    "studiobychar studio by char 47.webp"  = "studiobychar studio by char podcast set comparison a vs b.webp"
    "studiobychar studio by char 48.webp"  = "studiobychar studio by char podcast host red curly hair.webp"
    "studiobychar studio by char 49.webp"  = "studiobychar studio by char studio mezzanine sofa chair.webp"
    "studiobychar studio by char 50.webp"  = "studiobychar studio by char white chair green plants purple backdrop.webp"
    "studiobychar studio by char 51.webp"  = "studiobychar studio by char orange chair studio equipment.webp"
    "studiobychar studio by char 52.webp"  = "studiobychar studio by char mirror reflection studio hallway.webp"
    "studiobychar studio by char 53.webp"  = "studiobychar studio by char black chair purple backdrop.webp"
    "studiobychar studio by char 54.webp"  = "studiobychar studio by char white arch wall empty.webp"
    "studiobychar studio by char 55.webp"  = "studiobychar studio by char mirror against white curtains.webp"
    "studiobychar studio by char 56.webp"  = "studiobychar studio by char black chair purple backdrop wide.webp"
    "studiobychar studio by char 57.webp"  = "studiobychar studio by char white desk curtains mezzanine.webp"
    "studiobychar studio by char 58.webp"  = "studiobychar studio by char black chair purple backdrop v2.webp"
    "studiobychar studio by char 59.webp"  = "studiobychar studio by char white chair green plant purple backdrop v2.webp"
    "studiobychar studio by char 60.webp"  = "studiobychar studio by char white desk curtains mezzanine v2.webp"
    "studiobychar studio by char 61.webp"  = "studiobychar studio by char full length mirror white wall.webp"
    "studiobychar studio by char 62.webp"  = "studiobychar studio by char minimalist white desk.webp"
    "studiobychar studio by char 63.webp"  = "studiobychar studio by char black chair white desk studio.webp"
    "studiobychar studio by char 64.webp"  = "studiobychar studio by char white flower plant studio closeup.webp"
    "studiobychar studio by char 65.webp"  = "studiobychar studio by char grey sofa white wall plant.webp"
    "studiobychar studio by char 66.webp"  = "studiobychar studio by char orange chair minimalist studio.webp"
    "studiobychar studio by char 67.webp"  = "studiobychar studio by char grey sofa closeup v3.webp"
    "studiobychar studio by char 68.webp"  = "studiobychar studio by char grey sofa reflection.webp"
    "studiobychar studio by char 69.webp"  = "studiobychar studio by char grey sofa orange chair studio wide.webp"
    "studiobychar studio by char 70.webp"  = "studiobychar studio by char mirror blue purple backdrop wide.webp"
    "studiobychar studio by char 71.webp"  = "studiobychar studio by char podcast set a 1 pax wide.webp"
    "studiobychar studio by char 72.webp"  = "studiobychar studio by char white chair arch wall v2.webp"
    "studiobychar studio by char 73.webp"  = "studiobychar studio by char grey sofa orange chair wide v2.webp"
    "studiobychar studio by char 74.webp"  = "studiobychar studio by char studio lights stands black backdrop wide.webp"
    "studiobychar studio by char 75.webp"  = "studiobychar studio by char podcast set d 2 pax green chairs.webp"
    "studiobychar studio by char 76.webp"  = "studiobychar studio by char studio plant wide view mezzanine.webp"
    "studiobychar studio by char 77.webp"  = "studiobychar studio by char white flower studio closeup v2.webp"
    "studiobychar studio by char 78.webp"  = "studiobychar studio by char podcast set b 2 pax wide.webp"
    "studiobychar studio by char 79.webp"  = "studiobychar studio by char studio backdrop board chairs wide.webp"
    "studiobychar studio by char 80.webp"  = "studiobychar studio by char podcast set c 2 pax velvet sofa wide.webp"
    "studiobychar studio by char 81.webp"  = "studiobychar studio by char white chair green plant purple backdrop v3.webp"
    "studiobychar studio by char 82.webp"  = "studiobychar studio by char plants on long table studio wide v2.webp"
    "studiobychar studio by char 83.webp"  = "studiobychar studio by char grey sofa mirror wide v2.webp"
    "studiobychar studio by char 84.webp"  = "studiobychar studio by char grey sofa curtains mezzanine v2.webp"
    "studiobychar studio by char 85.webp"  = "studiobychar studio by char grey sofa mirror wide v3.webp"
    "studiobychar studio by char 86.webp"  = "studiobychar studio by char white chair green plant purple backdrop wide v4.webp"
    "studiobychar studio by char 87.webp"  = "studiobychar studio by char grey sofa mirror wide v4.webp"
    "studiobychar studio by char 88.webp"  = "studiobychar studio by char studio lights stands black backdrop wide v2.webp"
    "studiobychar studio by char 89.webp"  = "studiobychar studio by char white chair green plant purple backdrop wide v5.webp"
    "studiobychar studio by char 90.webp"  = "studiobychar studio by char grey sofa white curtains orange chair wide view.webp"
    "studiobychar studio by char 91.webp"  = "studiobychar studio by char white chair arch wall closeup v3.webp"
    "studiobychar studio by char 92.webp"  = "studiobychar studio by char podcast multi guest collage.webp"
    "studiobychar studio by char 93.webp"  = "studiobychar studio by char grey sofa mirror wide v5.webp"
    "studiobychar studio by char 94.webp"  = "studiobychar studio by char white chair green plant purple backdrop wide v6.webp"
    "studiobychar studio by char 95.webp"  = "studiobychar studio by char grey sofa closeup curtains v4.webp"
    "studiobychar studio by char 96.webp"  = "studiobychar studio by char grey sofa mirror curtains wide v6.webp"
    "studiobychar studio by char 97.webp"  = "studiobychar studio by char through curtains studio view v2.webp"
    "studiobychar studio by char 98.webp"  = "studiobychar studio by char three chairs comparison.webp"
    "studiobychar studio by char 99.webp"  = "studiobychar studio by char grey sofa orange chair curtains wide v3.webp"
    "studiobychar studio by char 100.webp" = "studiobychar studio by char minimal white studio table.webp"
    "studiobychar studio by char 101.webp" = "studiobychar studio by char white studio mezzanine curtains.webp"
    "studiobychar studio by char 102.webp" = "studiobychar studio by char minimal studio stools curtains.webp"
    "studiobychar studio by char 103.webp" = "studiobychar studio by char studio wide through curtains v3.webp"
    "studiobychar studio by char 104.webp" = "studiobychar studio by char grey sofa curtains wide perspective.webp"
    "studiobychar studio by char 105.webp" = "studiobychar studio by char white chair green plant purple backdrop v7.webp"
    "studiobychar studio by char 106.webp" = "studiobychar studio by char white chair green plant purple backdrop v8.webp"
    "studiobychar studio by char 107.webp" = "studiobychar studio by char black chair studio setup wide.webp"
    "studiobychar studio by char 108.webp" = "studiobychar studio by char black background lighting setup.webp"
    "studiobychar studio by char 109.webp" = "studiobychar studio by char white chair with plant purple backdrop.webp"
    "studiobychar studio by char 110.webp" = "studiobychar studio by char white studio room perspective curtains.webp"
    "studiobychar studio by char 111.webp" = "studiobychar studio by char white chair green plant purple backdrop v9.webp"
    "studiobychar studio by char 112.webp" = "studiobychar studio by char grey sofa through pink curtains.webp"
    "studiobychar studio by char 113.webp" = "studiobychar studio by char white chair green plant purple backdrop v10.webp"
    "studiobychar studio by char 114.webp" = "studiobychar studio by char white chair green plant purple backdrop v11.webp"
    "studiobychar studio by char 115.webp" = "studiobychar studio by char black chair studio arch wall.webp"
    "studiobychar studio by char 116.webp" = "studiobychar studio by char white chair green plant purple backdrop v12.webp"
    "studiobychar studio by char 117.webp" = "studiobychar studio by char black chair studio setup curtains.webp"
    "studiobychar studio by char 118.webp" = "studiobychar studio by char podcast mixer wicker chair set.webp"
    "studiobychar studio by char 119.webp" = "studiobychar studio by char grey sofa mirror perspective.webp"
    "studiobychar studio by char 120.webp" = "studiobychar studio by char white chair green plant studio v2.webp"
    "studiobychar studio by char 121.webp" = "studiobychar studio by char black chair studio setup wide perspective.webp"
    "studiobychar studio by char 122.webp" = "studiobychar studio by char black chair against arch wall closeup.webp"
    "studiobychar studio by char 123.webp" = "studiobychar studio by char black chair against arch wall wide.webp"
}

foreach ($oldName in $renames.Keys) {
    $oldPath = Join-Path $imagesDir $oldName
    $newName = $renames[$oldName]
    $newPath = Join-Path $imagesDir $newName
    if (Test-Path $oldPath) {
        Rename-Item -Path $oldPath -NewName $newName -Force
        Write-Host "Renamed $oldName to $newName"
    }
    elseif (Test-Path $newPath) {
        Write-Host "Skip: $newName already exists."
    }
    else {
        Write-Warning "File not found: $oldName"
    }
}
